// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

type Component struct {
	ID         int32
	ProductID  sql.NullInt32
	Name       string
	Specs      pqtype.NullRawMessage
	Quantity   int32
	AssignedTo sql.NullInt32
	Status     sql.NullString
	CreatedAt  sql.NullTime
}

type Organization struct {
	ID        int32
	Name      string
	OwnerID   sql.NullInt32
	CreatedAt sql.NullTime
}

type Product struct {
	ID          int32
	Name        string
	Description sql.NullString
	OwnerID     sql.NullInt32
	Status      sql.NullString
	CreatedAt   sql.NullTime
}

type User struct {
	ID        int32
	Username  string
	Password  string
	Email     string
	AvatarUrl sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
